### ISSUE TITLE
CMake Error: Could not find a package configuration file provided by "libOTe" 

### ISSUE THREAD

**Issue by jzhang12** [ucbrise/waldo#1]
I seem to be having issues with the libOTe and libPSI libraries when following build instructions. Below is the output/error I am getting: 
```
root@machine-1:/waldo# cmake .
-- The C compiler identification is GNU 11.2.0
-- The CXX compiler identification is GNU 11.2.0
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Check for working C compiler: /usr/bin/cc - skipped
-- Detecting C compile features
-- Detecting C compile features - done
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Check for working CXX compiler: /usr/bin/c++ - skipped
-- Detecting CXX compile features
-- Detecting CXX compile features - done
-- Option: DEBUG = OFF
-- Found Boost: /usr/lib/x86_64-linux-gnu/cmake/Boost-1.74.0/BoostConfig.cmake (found version "1.74.0")  
CMake Error at CMakeLists.txt:15 (find_package):
  By not providing "FindlibOTe.cmake" in CMAKE_MODULE_PATH this project has
  asked CMake to find a package configuration file provided by "libOTe", but
  CMake did not find one.

  Could not find a package configuration file provided by "libOTe" with any
  of the following names:

    libOTeConfig.cmake
    libote-config.cmake

  Add the installation prefix of "libOTe" to CMAKE_PREFIX_PATH or set
  "libOTe_DIR" to a directory containing one of the above files.  If "libOTe"
  provides a separate development package or SDK, be sure it has been
  installed.


-- Configuring incomplete, errors occurred!
See also "/waldo/CMakeFiles/CMakeOutput.log".
```

The configuration files are under /fss-core/cmake/ so I tried hinting `find_package` towards there. This resulted in a lot of similar errors that went something like: `Imported target [target] includes non existent path [filepath] in its INTERFACE_INCLUDE_DIRECTORIES.` 

 I'm using cmake version 3.22.1 and ubuntu 22.04 (also tried 20.04.4). Any help is appreciated.

**Comment by mayank0403** [comment]
Hi,

Thanks for your interest in our project!
This error might be coming because you didn't install libOTe and libPSI first.
Can you try the following -
Go to libOTe directory (shipped with our code) and use:
```
cmake . -DENABLE_RELIC=ON -DBOOST_ROOT="[boost-target-root-dir-absolute-path]" -DBoost_INCLUDE_DIR="[boost-target-root-dir-absolute-path]/include" -DENABLE_NP=ON -DENABLE_KKRT=ON

make -j
```

Go to libPSI directory and use:
```
cmake . -DENABLE_RELIC=ON -DBOOST_ROOT="[boost-target-root-dir-absolute-path]" -DBoost_INCLUDE_DIR="[boost-target-root-dir-absolute-path]/include" -DENABLE_DRRN_PSI=ON -DENABLE_KKRT_PSI=ON

make -j
```
After they are installed, try hinting the `find_package` again to where the configuration files are (`/fss-core/cmake/`).

**Comment by jzhang12** [comment]
Thank for for getting back to me! 

I was able to install the libOTe and libPSI libraries following your instructions. During the process, I had to build RELIC using `cmake . -DMULTI=OPENMP` and install it. I also had an issue in `/waldo/fss-core/libOTe/cryptoTools/cryptoTools/Crypto/RCurve.cpp` where a `bn_init()` function was not being recognized when building. This function call is actually commented out in the corresponding [file](https://github.com/ladnir/cryptoTools/blob/master/cryptoTools/Crypto/RCurve.cpp) from the cyrptoTools repo, so I just did the same. 

However, I am still getting errors with a "non-existent path" in INTERFACE_INCLUDE_DIRECTORIES. Below is a sample of the output/errors I am getting. I didn't include everything because there were a lot of errors and they are all very similar, so I suspect it's one issue.
```
root@machine-1:/waldo# cmake .
-- Option: DEBUG = OFF
-- Looking for pthread.h
-- Looking for pthread.h - found
-- Performing Test CMAKE_HAVE_LIBC_PTHREAD
-- Performing Test CMAKE_HAVE_LIBC_PTHREAD - Success
-- Found Threads: TRUE  
-- Finding Protobuf before gRPC
-- Found Protobuf: /usr/local/lib/libprotobuf.a (found version "3.19.4") 
-- Using gRPC 1.46.3
-- Using protobuf 3.19.4
-- Finding Protobuf before gRPC
-- Using gRPC 1.46.3
-- Using protobuf 3.19.4
-- Finding Protobuf before gRPC
-- Using gRPC 1.46.3
-- Using protobuf 3.19.4
-- Finding Protobuf before gRPC
-- Using gRPC 1.46.3
-- Using protobuf 3.19.4
-- Configuring done
CMake Error in fss-core/common/CMakeLists.txt:
  Imported target "libPSI_Tests" includes non-existent path

    "/home/ec2-user/dorydb/fss-core/libOTe/cmake/.."

  in its INTERFACE_INCLUDE_DIRECTORIES.  Possible reasons include:

  * The path was deleted, renamed, or moved to another location.

  * An install or uninstall procedure did not complete successfully.

  * The installation package was faulty and references files it does not
  provide.



CMake Error in fss-core/DPF-source/CMakeLists.txt:
  Imported target "libPSI_Tests" includes non-existent path

    "/home/ec2-user/dorydb/fss-core/libOTe/cmake/.."

  in its INTERFACE_INCLUDE_DIRECTORIES.  Possible reasons include:

  * The path was deleted, renamed, or moved to another location.

  * An install or uninstall procedure did not complete successfully.

  * The installation package was faulty and references files it does not
  provide.

```

The "non-existent path" always starts with `/home/ec2-user/dorydb/` which doesn't exist for me. Also, the target is either "libPSI_Tests" or "libOTe". I think I am supposed to try to get the file path to be  `/waldo/fss-core/ `... since that's where everything is installed for me, but I haven't figured out how to do that. Thanks again.

**Comment by mayank0403** [comment]
When you install libOTe and libPSI, the cmake config files are generated, and you need to copy them to `waldo/fss-core/cmake`.
You can find these files at: `waldo/fss-core/libOTe/libOTe_Tests/libOTeConfig.cmake` and `waldo/fss-core/libPSI/libPSI_Tests/libPSIConfig.cmake`.

**Comment by jzhang12** [comment]
The config files did not generate for me. I still only have the ones that came under `waldo/fss-core/cmake/`.

**Comment by edauterman** [comment]
Did you try installing libOTe and libPSI using the instructions [here](https://github.com/ucbrise/waldo/blob/main/fss-core/libOTe-PSI-instructions.md)? That should generate the cmake files @mayank0403 referred to, and then you can move them into `waldo/fss-core/cmake`. I updated the documentation and removed the stale cmake file to hopefully avoid further confusion about this. Let me know if you're still having trouble.

**Comment by jzhang12** [comment]
Since libOTe and libPSI are shipped with the code, I skipped that part in the instructions that say to clone them again. Besides that I did everything else. I think I've managed to install the libraries as I can run all the unit tests (minus a couple of the libPSI ones which get runtime error). However, the config files are not generated for me.

**Comment by jzhang12** [comment]
Bumping my issue since I am still having trouble. 

Even though the libraries are shipped with the code, I tried deleting them and then re-cloning them again just in case there was something I was missing. Since it seems that the libraries shipped with waldo are not the same as the current versions of libOTe/libPSI, I also tried this with their older releases. I didn't manage to get any of these to build, so I'm thinking that this is not what I should be doing? 

So far, the furthest I've gotten is using the libPSI/libOTe that is shipped with the code. For some reason the config files are not showing up. Not sure what to try next. Any help appreciated.

**Comment by edauterman** [comment]
Sorry for the delayed response. If you're able to run all the waldo tests, then the waldo code should be working just fine with the dependencies. The config files might be an artifact of an older version of the build process before we released the code. I'll look into this and update the README instructions to avoid future confusion. Let me know if you're having trouble getting the waldo code to run -- otherwise, don't worry about the config file generation.

**Comment by jzhang12** [comment]
Should I be following the same build instructions as in the README? The `find_package` lines in the cmake file seem to require the config files that I'm missing so I commented those two lines out. Cmake will generate the build files, but the code won't link. In case it is helpful, here is what I am currently getting as output/error: 

```
root@machine-1:/waldo# cmake .
-- The C compiler identification is GNU 9.4.0
-- The CXX compiler identification is GNU 9.4.0
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Check for working C compiler: /usr/bin/cc - skipped
-- Detecting C compile features
-- Detecting C compile features - done
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Check for working CXX compiler: /usr/bin/c++ - skipped
-- Detecting CXX compile features
-- Detecting CXX compile features - done
-- Option: DEBUG = OFF
-- Found Boost: /usr/local/lib/cmake/Boost-1.76.0/BoostConfig.cmake (found version "1.76.0")  
-- Performing Test CMAKE_HAVE_LIBC_PTHREAD
-- Performing Test CMAKE_HAVE_LIBC_PTHREAD - Success
-- Found Threads: TRUE  
-- Finding Protobuf before gRPC
-- Found Protobuf: /usr/local/lib/libprotobuf.a (found version "3.19.4") 
-- Using gRPC 1.46.3
-- Using protobuf 3.19.4
-- Finding Protobuf before gRPC
-- Using gRPC 1.46.3
-- Using protobuf 3.19.4
-- Finding Protobuf before gRPC
-- Using gRPC 1.46.3
-- Using protobuf 3.19.4
-- Finding Protobuf before gRPC
-- Using gRPC 1.46.3
-- Using protobuf 3.19.4
-- Configuring done
-- Generating done
-- Build files have been written to: /waldo
root@machine-1:/waldo# make
Consolidate compiler generated dependencies of target FSSCoreCommon
[  2%] Built target FSSCoreCommon
Consolidate compiler generated dependencies of target DPFClient
[  5%] Built target DPFClient
Consolidate compiler generated dependencies of target DPFServer
[  7%] Built target DPFServer
Consolidate compiler generated dependencies of target DCFClient
[ 10%] Built target DCFClient
Consolidate compiler generated dependencies of target DCFServer
[ 13%] Built target DCFServer
Consolidate compiler generated dependencies of target DPF_unit_test
[ 14%] Linking CXX executable ../../build/bin/DPF_unit_test
/usr/bin/ld: cannot find -llibOTe
/usr/bin/ld: cannot find -llibPSI_Tests
/usr/bin/ld: cannot find -llibOTe
/usr/bin/ld: cannot find -llibPSI_Tests
/usr/bin/ld: cannot find -lcryptoTools
collect2: error: ld returned 1 exit status
make[2]: *** [fss-core/tests/CMakeFiles/DPF_unit_test.dir/build.make:102: build/bin/DPF_unit_test] Error 1
make[1]: *** [CMakeFiles/Makefile2:547: fss-core/tests/CMakeFiles/DPF_unit_test.dir/all] Error 2
make: *** [Makefile:91: all] Error 2
```

**Comment by vasia** [comment]
Dear @edauterman, I have also tried the current readme instructions and, unfortunately, ran into the errors reported above. An updated list of dependencies with expected versions and/or updated installation instructions will be greatly appreciated. Thank you!

**Comment by edauterman** [comment]
Thanks for clarifying, misunderstood your earlier comment. What output do you get when you run the instructions to install libPSI and libOTe [here](https://github.com/ucbrise/waldo/blob/main/fss-core/libOTe-PSI-instructions.md)? The instructions have [Relic](https://github.com/relic-toolkit/relic) enabled by default, which should also be installed.

**Comment by jzhang12** [comment]
@edauterman As far as I can tell I have been able to successfully install both libPSI and libOTe that is shipped with the code. Here are the outputs below after running `make -j`. For Relic, I installed it with OpenMP enabled. Also, for libOTe I had to make a small change by commenting out the line `bn_init()` in RCurve.cpp (otherwise it won't compile). The unit tests for both libOTe and libPSI are working. Below is the output I am getting. 

libOTe:
```
-- The ASM compiler identification is GNU
-- Found assembler: /usr/bin/cc
-- Found OpenMP_C: -fopenmp (found version "4.5") 
-- Found OpenMP_CXX: -fopenmp (found version "4.5") 
-- Found OpenMP: TRUE (found version "4.5")  
-- Configuring done
-- Generating done
-- Build files have been written to: /waldo/fss-core/libOTe
root@machine-1:/waldo/fss-core/libOTe# make -j
Consolidate compiler generated dependencies of target cryptoTools
[ 32%] Built target cryptoTools
Consolidate compiler generated dependencies of target tests_cryptoTools
Consolidate compiler generated dependencies of target libOTe
[ 47%] Built target tests_cryptoTools
Consolidate compiler generated dependencies of target frontend_cryptoTools
[ 83%] Built target libOTe
[ 87%] Built target frontend_cryptoTools
Consolidate compiler generated dependencies of target libOTe_Tests
[ 96%] Built target libOTe_Tests
Consolidate compiler generated dependencies of target frontend_libOTe
[100%] Built target frontend_libOTe
root@machine-1:/waldo/fss-core/libOTe# 

```

libPSI:
```
root@machine-1:/waldo/fss-core/libPSI# make -j
Consolidate compiler generated dependencies of target libPSI
[ 57%] Built target libPSI
Consolidate compiler generated dependencies of target libPSI_Tests
[ 78%] Built target libPSI_Tests
Consolidate compiler generated dependencies of target frontend.exe
[100%] Built target frontend.exe
root@machine-1:/waldo/fss-core/libPSI#
```

**Comment by jzhang12** [comment]
My issue is that I still can't get Waldo itself to build, despite getting the libraries working. You mentioned above that I shouldn't need to worry about the config files, but It seems CMakeLists is looking for them specifically with the `find_package` lines. Below is the output I am getting after running the second `cmake . ` from your build instructions. 

I did try commenting out the find_package lines for libOTe and libPSI, but to no avail. I posted the output I got from trying this above. 

```
root@machine-1:/waldo# cmake .
-- The C compiler identification is GNU 9.4.0
-- The CXX compiler identification is GNU 9.4.0
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Check for working C compiler: /usr/bin/cc - skipped
-- Detecting C compile features
-- Detecting C compile features - done
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Check for working CXX compiler: /usr/bin/c++ - skipped
-- Detecting CXX compile features
-- Detecting CXX compile features - done
-- Option: DEBUG = OFF
-- Found Boost: /usr/local/lib/cmake/Boost-1.76.0/BoostConfig.cmake (found version "1.76.0")  
CMake Error at CMakeLists.txt:15 (find_package):
  By not providing "FindlibOTe.cmake" in CMAKE_MODULE_PATH this project has
  asked CMake to find a package configuration file provided by "libOTe", but
  CMake did not find one.

  Could not find a package configuration file provided by "libOTe" with any
  of the following names:

    libOTeConfig.cmake
    libote-config.cmake

  Add the installation prefix of "libOTe" to CMAKE_PREFIX_PATH or set
  "libOTe_DIR" to a directory containing one of the above files.  If "libOTe"
  provides a separate development package or SDK, be sure it has been
  installed.


-- Configuring incomplete, errors occurred!
See also "/waldo/CMakeFiles/CMakeOutput.log".
```

**Comment by mayank0403** [comment]
Sorry for the delay. Instructions for building the project have been updated. Please follow the new instructions. I tried installing the project from scratch using them on a fresh ec2 instance and they work for me. Let me know if you face any issues. 

Thanks!

**Comment by jzhang12** [comment]
I got it to work! Thank you for the help.
