### ISSUE TITLE
Error while running correctness test on user defined data 

### ISSUE THREAD

**Issue by komalkumaridev** [ucbrise/waldo#2]
Hi Team,

I have updated the function "dpfAggTest"  in client/tests/correctness_tests.cpp as below:

Line 22:  cond.x = 12;
Line 33: uint32_t numBuckets = 4;
Line 34: uint32_t windowSize = 4;
Line 35:  vector<uint128_t> dataVals{(uint128_t)12,(uint128_t)12,(uint128_t)2,(uint128_t)4}
Line 36:  vector<uint32_t> dcfVals{(uint32_t)12,(uint32_t)12,(uint32_t)2,(uint32_t)4};

As per my understanding, Waldo will find aggregate on records with 12 as their values. I get the below error when running ./build/bin/correctness_tests.

Malicious security with 61 bit statistical security: ON
batch= 0/0
malloc(): invalid size (unsorted)
Aborted (core dumped)

Where am I going wrong and what is the difference between the dataVals and dcfVals? I understand dataVals stores the actual data for each record for a given feature(this will help to compute the sum function), but what is dcfVals storing? As a user, if I have 10 records with a feature 'A' storing values as [1,2,3,4,5,6,7,8,9,10]  for those 10 records, how should my dcfVals vector looks like?

**Comment by edauterman** [comment]
dataVals is the values that you're aggregating, and dcfVals is the values that you're comparing to. windowSize is the number of records, and numBuckets is the range of dcfVals. The problem that you're running into here is that the values in dcfVals need to be in the range 0 to numBuckets - 1. If you replace the values in dcfVals with values in the range 0 to numBuckets - 1 or increase numBuckets to 16, this should fix the problem.

**Comment by komalkumaridev** [comment]
Thank you for guiding me. Much appreciated!!
