### ISSUE TITLE
ERROR：waldo/network/core/query.pb.h:358:12: error: ‘absl’ in namespace ‘::’ does not name a type; did you mean ‘abs’?   358 |   static ::absl::string_view FullMessageName() .    

### ISSUE THREAD

**Issue by mufeng-74** [ucbrise/waldo#3]
Hello, when I execute the make command of network, I encounter the following error:

In file included from /home/user/library/waldo/network/core/query.pb.cc:4:
/home/user/library/waldo/network/core/query.pb.h:358:12: error: ‘absl’ in namespace ‘::’ does not name a type; did you mean ‘abs’?
  358 |   static ::absl::string_view FullMessageName() {
      |            ^~~~
      |            abs
/home/user/library/waldo/network/core/query.pb.h:510:12: error: ‘absl’ in namespace ‘::’ does not name a type; did you mean ‘abs’?
  510 |   static ::absl::string_view FullMessageName() {
      |            ^~~~
      |            abs
/home/user/library/waldo/network/core/query.pb.h:662:12: error: ‘absl’ in namespace ‘::’ does not name a type; did you mean ‘abs’?
  662 |   static ::absl::string_view FullMessageName() {
      |            ^~~~
      |            abs
/home/user/library/waldo/network/core/query.pb.h:847:12: error: ‘absl’ in namespace ‘::’ does not name a type; did you mean ‘abs’?
  847 |   static ::absl::string_view FullMessageName() {
      |            ^~~~
      |            abs
/home/user/library/waldo/network/core/query.pb.h:999:12: error: ‘absl’ in namespace ‘::’ does not name a type; did you mean ‘abs’?
  999 |   static ::absl::string_view FullMessageName() {
      |            ^~~~
      |            abs
/home/user/library/waldo/network/core/query.pb.h:1184:12: error: ‘absl’ in namespace ‘::’ does not name a type; did you mean ‘abs’?
 1184 |   static ::absl::string_view FullMessageName() {
      |            ^~~~
      |            abs
/home/user/library/waldo/network/core/query.pb.h:1336:12: error: ‘absl’ in namespace ‘::’ does not name a type; did you mean ‘abs’?
 1336 |   static ::absl::string_view FullMessageName() {
      |            ^~~~
      |            abs
/home/user/library/waldo/network/core/query.pb.h:1499:12: error: ‘absl’ in namespace ‘::’ does not name a type; did you mean ‘abs’?
 1499 |   static ::absl::string_view FullMessageName() {
      |            ^~~~
      |            abs
/home/user/library/waldo/network/core/query.pb.h:1651:12: error: ‘absl’ in namespace ‘::’ does not name a type; did you mean ‘abs’?
 1651 |   static ::absl::string_view FullMessageName() {
      |            ^~~~
      |            abs
/home/user/library/waldo/network/core/query.pb.h:1825:12: error: ‘absl’ in namespace ‘::’ does not name a type; did you mean ‘abs’?
 1825 |   static ::absl::string_view FullMessageName() {
      |            ^~~~
      |            abs
/home/user/library/waldo/network/core/query.pb.h:1977:12: error: ‘absl’ in namespace ‘::’ does not name a type; did you mean ‘abs’?
 1977 |   static ::absl::string_view FullMessageName() {
      |            ^~~~
      |            abs
/home/user/library/waldo/network/core/query.pb.h:2172:12: error: ‘absl’ in namespace ‘::’ does not name a type; did you mean ‘abs’?
 2172 |   static ::absl::string_view FullMessageName() {
      |            ^~~~
      |            abs
/home/user/library/waldo/network/core/query.pb.h:2328:12: error: ‘absl’ in namespace ‘::’ does not name a type; did you mean ‘abs’?
 2328 |   static ::absl::string_view FullMessageName() {
      |            ^~~~
      |            abs
In file included from /home/user/library/waldo/network/core/query.pb.cc:4:
/home/user/library/waldo/network/core/query.pb.h:2480:12: error: ‘absl’ in namespace ‘::’ does not name a type; did you mean ‘abs’?
 2480 |   static ::absl::string_view FullMessageName() {
      |            ^~~~
      |            abs
/home/user/library/waldo/network/core/query.pb.h:2632:12: error: ‘absl’ in namespace ‘::’ does not name a type; did you mean ‘abs’?
 2632 |   static ::absl::string_view FullMessageName() {
      |            ^~~~
      |            abs
/home/user/library/waldo/network/core/query.pb.h:2827:12: error: ‘absl’ in namespace ‘::’ does not name a type; did you mean ‘abs’?
 2827 |   static ::absl::string_view FullMessageName() {
      |            ^~~~
      |            abs
/home/user/library/waldo/network/core/query.pb.h:2983:12: error: ‘absl’ in namespace ‘::’ does not name a type; did you mean ‘abs’?
 2983 |   static ::absl::string_view FullMessageName() {
      |            ^~~~
      |            abs
/home/user/library/waldo/network/core/query.pb.h:3135:12: error: ‘absl’ in namespace ‘::’ does not name a type; did you mean ‘abs’?
 3135 |   static ::absl::string_view FullMessageName() {
      |            ^~~~
      |            abs
/home/user/library/waldo/network/core/query.pb.h:3287:12: error: ‘absl’ in namespace ‘::’ does not name a type; did you mean ‘abs’?
 3287 |   static ::absl::string_view FullMessageName() {
      |            ^~~~
      |            abs
/home/user/library/waldo/network/core/query.pb.h:3482:12: error: ‘absl’ in namespace ‘::’ does not name a type; did you mean ‘abs’?
 3482 |   static ::absl::string_view FullMessageName() {
      |            ^~~~
      |            abs
/home/user/library/waldo/network/core/query.pb.h:3638:12: error: ‘absl’ in namespace ‘::’ does not name a type; did you mean ‘abs’?
 3638 |   static ::absl::string_view FullMessageName() {
      |            ^~~~
      |            abs
/home/user/library/waldo/network/core/query.pb.h:3790:12: error: ‘absl’ in namespace ‘::’ does not name a type; did you mean ‘abs’?
 3790 |   static ::absl::string_view FullMessageName() {
      |            ^~~~
      |            abs
/home/user/library/waldo/network/core/query.pb.h:3942:12: error: ‘absl’ in namespace ‘::’ does not name a type; did you mean ‘abs’?
 3942 |   static ::absl::string_view FullMessageName() {
      |            ^~~~
      |            abs
/home/user/library/waldo/network/core/query.pb.h:4105:12: error: ‘absl’ in namespace ‘::’ does not name a type; did you mean ‘abs’?
 4105 |   static ::absl::string_view FullMessageName() {
      |            ^~~~
      |            abs
/home/user/library/waldo/network/core/query.pb.h:4293:12: error: ‘absl’ in namespace ‘::’ does not name a type; did you mean ‘abs’?
 4293 |   static ::absl::string_view FullMessageName() {
      |            ^~~~
      |            abs
/home/user/library/waldo/network/core/query.pb.h:4508:12: error: ‘absl’ in namespace ‘::’ does not name a type; did you mean ‘abs’?
 4508 |   static ::absl::string_view FullMessageName() {
      |            ^~~~
      |            abs
/home/user/library/waldo/network/core/query.pb.h:4660:12: error: ‘absl’ in namespace ‘::’ does not name a type; did you mean ‘abs’?
 4660 |   static ::absl::string_view FullMessageName() {
      |            ^~~~
      |            abs
/home/user/library/waldo/network/core/query.pb.h:4844:12: error: ‘absl’ in namespace ‘::’ does not name a type; did you mean ‘abs’?
 4844 |   static ::absl::string_view FullMessageName() {
      |            ^~~~
      |            abs
/home/user/library/waldo/network/core/query.pb.h:4996:12: error: ‘absl’ in namespace ‘::’ does not name a type; did you mean ‘abs’?
 4996 |   static ::absl::string_view FullMessageName() {
      |            ^~~~
      |            abs
/home/user/library/waldo/network/core/query.pb.h:5164:12: error: ‘absl’ in namespace ‘::’ does not name a type; did you mean ‘abs’?
 5164 |   static ::absl::string_view FullMessageName() {
      |            ^~~~
      |            abs
/home/user/library/waldo/network/core/query.pb.h:5316:12: error: ‘absl’ in namespace ‘::’ does not name a type; did you mean ‘abs’?
 5316 |   static ::absl::string_view FullMessageName() {
      |            ^~~~
      |            abs
/home/user/library/waldo/network/core/query.pb.h:5500:12: error: ‘absl’ in namespace ‘::’ does not name a type; did you mean ‘abs’?
 5500 |   static ::absl::string_view FullMessageName() {
      |            ^~~~
      |            abs
/home/user/library/waldo/network/core/query.pb.h:5700:12: error: ‘absl’ in namespace ‘::’ does not name a type; did you mean ‘abs’?
 5700 |   static ::absl::string_view FullMessageName() {
      |            ^~~~
      |            abs
/home/user/library/waldo/network/core/query.pb.h:5895:12: error: ‘absl’ in namespace ‘::’ does not name a type; did you mean ‘abs’?
 5895 |   static ::absl::string_view FullMessageName() {
      |            ^~~~
      |            abs
/home/user/library/waldo/network/core/query.pb.h:6062:12: error: ‘absl’ in namespace ‘::’ does not name a type; did you mean ‘abs’?
 6062 |   static ::absl::string_view FullMessageName() {
      |            ^~~~
      |            abs
/home/user/library/waldo/network/core/query.pb.h:6234:12: error: ‘absl’ in namespace ‘::’ does not name a type; did you mean ‘abs’?
 6234 |   static ::absl::string_view FullMessageName() {
      |            ^~~~
      |            abs
/home/user/library/waldo/network/core/query.pb.h:6434:12: error: ‘absl’ in namespace ‘::’ does not name a type; did you mean ‘abs’?
 6434 |   static ::absl::string_view FullMessageName() {
      |            ^~~~
      |            abs
/home/user/library/waldo/network/core/query.pb.h:6586:12: error: ‘absl’ in namespace ‘::’ does not name a type; did you mean ‘abs’?
 6586 |   static ::absl::string_view FullMessageName() {
      |            ^~~~
      |            abs
/home/user/library/waldo/network/core/query.pb.cc:1155:10: error: ‘absl’ in namespace ‘::’ does not name a type; did you mean ‘abs’?
 1155 | static ::absl::once_flag descriptor_table_query_2eproto_once;
      |          ^~~~
      |          abs

I have installed all the libraries required for compilation, but I still encounter the following problems. I want to know if it is because the source code in the waldo library has Problems, and how should I fix them, thanks a lot for your answers!

**Comment by edauterman** [comment]
From this error message and the error message in your other issue, this looks like a problem with your installation of grpc and/or protobuf.

**Comment by mufeng-74** [comment]
Thank you very much for your reply!
But my grpc and protobuf libraries did not report errors during the previous installation process. protoc --version can also display the version number. Is there any other possibility of errors, or I need to check the installation of my grpc again.
