### ISSUE TITLE
ERROR: ‘descriptor_table_query_2eproto_once’ was not declared in this scope; did you mean ‘descriptor_table_query_2eproto_getter’?  1392 |       &descriptor_table_query_2eproto_getter, &descriptor_table_query_2eproto_once,

### ISSUE THREAD

**Issue by mufeng-74** [ucbrise/waldo#4]
Hello, when I execute the make command of the network library, the following errors also appear. How should I solve them?

/home/user/library/waldo/network/core/query.pb.cc: In member function ‘virtual google::protobuf::Metadata dbquery::InitSystemResponse::GetMetadata() const’:
/home/user/library/waldo/network/core/query.pb.cc:1595:48: error: ‘descriptor_table_query_2eproto_once’ was not declared in this scope; did you mean ‘descriptor_table_query_2eproto_getter’?
 1595 |       &descriptor_table_query_2eproto_getter, &descriptor_table_query_2eproto_once,

**Comment by edauterman** [comment]
From this error message and the error message in your other issue, this looks like a problem with your installation of grpc and/or protobuf.
