### ISSUE TITLE
Issue with building the network point

### ISSUE THREAD

**Issue by karthik8239** [ucbrise/waldo#9]
I am having the issue with the network command setup.
I installed all the tools gRPC, boost , and relic successfully.
as separate folders in a ubuntu setup.Able to build the libOTe and libPSI as well.But I am facing the issue of at Building the network setup at the step ->  "make".
I am just posting the screenshots of the issue which I am facing .I guess it is with the code.
could you please point me in a direction to resolve this issue?
link provided for the  repository I am referring to.
![Code_network_waldo](https://github.com/ucbrise/waldo/assets/43171496/ab700aa3-8701-41d1-a13f-af9dae808985)

**Comment by edauterman** [comment]
It looks like you haven't installed the protobuf library as part of gRPC (install gRPC with protobuf using instructions here: https://grpc.io/docs/languages/cpp/quickstart/).
